@startmindmap
+[#red] 总体

++[#lightgreen] 应用分析与最佳实践
+++ 为什么用Mybatis
++++_ JDBC
++++_ 一些工具类
++++_ 什么是ORM框架
++++_ Mybatis特性总结

+++ 不用容器，Mybatis怎么用？
+++ Mybatis的高级用法与扩展

++[#lightgreen] 体系接口与工作原理
+++ 为什么用
++[#lightgreen] 体系接口与工作原理
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++[#lightgreen] 体系接口与工作原理
+++ 为什么用
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
+++ 为什么用
+++ 为什么用
++[#lightgreen] 体系接口与工作原理
+++ 为什么用
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具

++[#lightgreen] 体系接口与工作原理
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++[#lightgreen] 体系接口与工作原理
+++ 为什么用
++[#lightgreen] 体系接口与工作原理
+++ 为什么用
++[#lightgreen] 体系接口与工作原理
+++ 为什么用
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
++++_ 一些工具
+++ 为什么用
++++_ 一些工具
++++_ 一些工具

--[#lightgreen] 插件原理与Spring集成
--- 总结
----_ 核心对象与设计模式总结
--- 插件原理
----_ 如何使用插件
----_ 插件的原理
----_ 如何编写自己的插件
--- Spring集成原理
----_ 集成原理
--[#lightgreen] 手写Mybatis
--- 插件原理
--[#lightgreen] 手写Mybatis
--- 插件原理
----_ 如何使用
----_ 如何使用
--- 插件原理
----_ 如何使用
----_ 如何使用
--[#lightgreen] 手写Mybatis
--- 插件原理
--- 插件原理
----_ 如何使用
--- 插件原理
----_ 如何使用
----_ 如何使用
--- 插件原理
--[#lightgreen] 手写Mybatis
--- 插件原理
--[#lightgreen] 手写Mybatis
--- 插件原理
----_ 如何使用
--[#lightgreen] 手写Mybatis
--- 插件原理
----_ 如何使用
--[#lightgreen] 手写Mybatis
--- 插件原理
----_ 如何使用
--[#lightgreen] 手写Mybatis
--- 插件原理
----_ 如何使用
--[#lightgreen] 手写Mybatis
--- 插件原理
----_ 如何使用

@endmindmap
