package com.jixs.mybatisplus.mapper;

import com.jixs.mybatisplus.po.TUser;
import java.util.List;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    List<TUser> selectAll();
}