package com.jixs.mybatis.po;

public class TfGsAttr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_gs_attr.ORD_ID
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    private String ordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_gs_attr.ATTR_CODE
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    private String attrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_gs_attr.ATTR_VALUE
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    private String attrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_gs_attr.ATTR_NAME
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_gs_attr.UPDATE_TAG
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    private String updateTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_gs_attr.TENANT_ID
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_gs_attr.ORD_ID
     *
     * @return the value of tf_gs_attr.ORD_ID
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public String getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_gs_attr.ORD_ID
     *
     * @param ordId the value for tf_gs_attr.ORD_ID
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public void setOrdId(String ordId) {
        this.ordId = ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_gs_attr.ATTR_CODE
     *
     * @return the value of tf_gs_attr.ATTR_CODE
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_gs_attr.ATTR_CODE
     *
     * @param attrCode the value for tf_gs_attr.ATTR_CODE
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_gs_attr.ATTR_VALUE
     *
     * @return the value of tf_gs_attr.ATTR_VALUE
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_gs_attr.ATTR_VALUE
     *
     * @param attrValue the value for tf_gs_attr.ATTR_VALUE
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_gs_attr.ATTR_NAME
     *
     * @return the value of tf_gs_attr.ATTR_NAME
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_gs_attr.ATTR_NAME
     *
     * @param attrName the value for tf_gs_attr.ATTR_NAME
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_gs_attr.UPDATE_TAG
     *
     * @return the value of tf_gs_attr.UPDATE_TAG
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public String getUpdateTag() {
        return updateTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_gs_attr.UPDATE_TAG
     *
     * @param updateTag the value for tf_gs_attr.UPDATE_TAG
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public void setUpdateTag(String updateTag) {
        this.updateTag = updateTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_gs_attr.TENANT_ID
     *
     * @return the value of tf_gs_attr.TENANT_ID
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_gs_attr.TENANT_ID
     *
     * @param tenantId the value for tf_gs_attr.TENANT_ID
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}