package com.jixs.mybatis.mapper;

import com.jixs.mybatis.po.TfGsAttr;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TfGsAttrMapper {
    List<TfGsAttr> qryByOrdId(@Param("ordId") String ordId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_gs_attr
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    int deleteByPrimaryKey(@Param("ordId") String ordId, @Param("attrCode") String attrCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_gs_attr
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    int insert(TfGsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_gs_attr
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    TfGsAttr selectByPrimaryKey(@Param("ordId") String ordId, @Param("attrCode") String attrCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_gs_attr
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    List<TfGsAttr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_gs_attr
     *
     * @mbg.generated Thu Jul 23 11:20:52 CST 2020
     */
    int updateByPrimaryKey(TfGsAttr record);
}